export const dashboardConstants = {
  DASH_GET_ALL_REQUEST: 'DASH_GET_ALL_REQUEST',
  DASH_GET_ALL_SUCCESS: 'DASH_GET_ALL_SUCCESS',
  DASH_GET_ALL_FAILURE: 'DASH_GET_ALL_FAILURE',

  DASH_SET_ACTIVE_USER_REQUEST: 'DASH_SET_ACTIVE_USER_REQUEST',
  DASH_SET_ACTIVE_USER_SUCCESS: 'DASH_SET_ACTIVE_USER_SUCCESS',
  DASH_SET_ACTIVE_USER_FAILURE: 'DASH_SET_ACTIVE_USER_FAILURE'
};
