export const authConstants = {
  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT'
};

export const catsConstants = {
  CATS_GET_FACTS_REQUEST: 'CATS_GET_FACTS_REQUEST',
  CATS_GET_FACTS_SUCCESS: 'CATS_GET_FACTS_SUCCESS',
  CATS_GET_FACTS_FAILURE: 'CATS_GET_FACTS_FAILURE'
};

export const dashboardConstants = {
  DASH_GET_ALL_REQUEST: 'DASH_GET_ALL_REQUEST',
  DASH_GET_ALL_SUCCESS: 'DASH_GET_ALL_SUCCESS',
  DASH_GET_ALL_FAILURE: 'DASH_GET_ALL_FAILURE',

  DASH_SET_ACTIVE_USER_REQUEST: 'DASH_SET_ACTIVE_USER_REQUEST',
  DASH_SET_ACTIVE_USER_SUCCESS: 'DASH_SET_ACTIVE_USER_SUCCESS',
  DASH_SET_ACTIVE_USER_FAILURE: 'DASH_SET_ACTIVE_USER_FAILURE'
};

export const punksConstants = {
  PUNKS_GET_BEERS_REQUEST: 'PUNKS_GET_BEERS_REQUEST',
  PUNKS_GET_BEERS_SUCCESS: 'PUNKS_GET_BEERS_SUCCESS',
  PUNKS_GET_BEERS_FAILURE: 'PUNKS_GET_BEERS_FAILURE'
};

export const swapiConstants = {
  SW_PEOPLE_REQUEST: 'SW_PEOPLE_REQUEST',
  SW_PEOPLE_SUCCESS: 'SW_PEOPLE_SUCCESS',
  SW_PEOPLE_FAILURE: 'SW_PEOPLE_FAILURE'
};

export const userConstants = {
  USER_ADD_REQUEST: 'USER_ADD_REQUEST',
  USER_ADD_SUCCESS: 'USER_ADD_SUCCESS',
  USER_ADD_FAILURE: 'USER_ADD_FAILURE',

  USER_DELETE_REQUEST: 'USER_DELETE_REQUEST',
  USER_DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
  USER_DELETE_FAILURE: 'USER_DELETE_FAILURE',

  USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
  USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
  USER_UPDATE_FAILURE: 'USER_UPDATE_FAILURE',

  USER_SET_ACTIVE_FOR_UPDATE_REQUEST: 'USER_SET_ACTIVE_FOR_UPDATE_REQUEST',
  USER_SET_ACTIVE_FOR_UPDATE_SUCCESS: 'USER_SET_ACTIVE_FOR_UPDATE_SUCCESS',
  USER_SET_ACTIVE_FOR_UPDATE_FAILURE: 'USER_SET_ACTIVE_FOR_UPDATE_FAILURE',

  USER_DELETE_ACTIVE_FOR_UPDATE_REQUEST: 'USER_DELETE_ACTIVE_FOR_UPDATE_REQUEST',
  USER_DELETE_ACTIVE_FOR_UPDATE_SUCCESS: 'USER_DELETE_ACTIVE_FOR_UPDATE_SUCCESS',
  USER_DELETE_ACTIVE_FOR_UPDATE_FAILURE: 'USER_DELETE_ACTIVE_FOR_UPDATE_FAILURE',

  USER_REMOVE_ALL_REQUEST: 'USER_REMOVE_ALL_REQUEST',
  USER_REMOVE_ALL_SUCCESS: 'USER_REMOVE_ALL_SUCCESS',
  USER_REMOVE_ALL_FAILURE: 'USER_REMOVE_ALL_FAILURE'
};
