export const userConstants = {
  USER_ADD_REQUEST: 'USER_ADD_REQUEST',
  USER_ADD_SUCCESS: 'USER_ADD_SUCCESS',
  USER_ADD_FAILURE: 'USER_ADD_FAILURE',

  USER_DELETE_REQUEST: 'USER_DELETE_REQUEST',
  USER_DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
  USER_DELETE_FAILURE: 'USER_DELETE_FAILURE',

  USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
  USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
  USER_UPDATE_FAILURE: 'USER_UPDATE_FAILURE',

  USER_SET_ACTIVE_FOR_UPDATE_REQUEST: 'USER_SET_ACTIVE_FOR_UPDATE_REQUEST',
  USER_SET_ACTIVE_FOR_UPDATE_SUCCESS: 'USER_SET_ACTIVE_FOR_UPDATE_SUCCESS',
  USER_SET_ACTIVE_FOR_UPDATE_FAILURE: 'USER_SET_ACTIVE_FOR_UPDATE_FAILURE',

  USER_DELETE_ACTIVE_FOR_UPDATE_REQUEST: 'USER_DELETE_ACTIVE_FOR_UPDATE_REQUEST',
  USER_DELETE_ACTIVE_FOR_UPDATE_SUCCESS: 'USER_DELETE_ACTIVE_FOR_UPDATE_SUCCESS',
  USER_DELETE_ACTIVE_FOR_UPDATE_FAILURE: 'USER_DELETE_ACTIVE_FOR_UPDATE_FAILURE',

  USER_REMOVE_ALL_REQUEST: 'USER_REMOVE_ALL_REQUEST',
  USER_REMOVE_ALL_SUCCESS: 'USER_REMOVE_ALL_SUCCESS',
  USER_REMOVE_ALL_FAILURE: 'USER_REMOVE_ALL_FAILURE'
};
